#!/bin/bash
set -ex

export DOTNET_ROOT="/srv/conda/envs/notebook/lib/dotnet"
export PATH=$PATH:$DOTNET_ROOT:~/.dotnet/tools
dotnet tool install -g Microsoft.dotnet-interactive
dotnet interactive jupyter install
